# High Level System Landscape
#
vars: {
  d2-config: {
        layout-engine: elk  
  }
}
direction: down

# External
obs: Observing Platform {
  direction: down
  gliders: Gliders
  bottom: Bottom Mounted Platforms
  buoy: Moored Buoys
  ship: Research Vessels
}

operator: PAM Operator {
  shape: c4-person
}
analyst: PAM Analyst {
  shape: c4-person
}
# Internal PAMHUB is the main system in question
# Stakeholder engagement will help determine the needed functionality of the Data Processing container.
pamhub: "PAMHUB" {
  shape: rectangle
  label.near: bottom-left

  ingest: Ingest {
    shape: rectangle
    CLI
    Transport Service
    Upload Portal
  }
  storage: Storage {
    bucket: Object Storage Bucket {
      shape: cylinder
    }
    archive-bucket: Archive Staging Bucket {
      shape: cylinder
    }
    database: Metadata and Detection Database {
      shape: cylinder
    }
  }
  processing: Processing {
    pam-ww: Data Processing Workstation {
      shape: rectangle
    }
    batch: Orchestration Workflow {
      shape: package
    }
  }
  export: Export Products {
    archive-formatter
    pacm-formatter
    hmd-visualization-formatter
    hmd-climatology-formatter
  }
  operations: Operations {
    Monitoring
    Alerts
    Cost Management
  }
}

# More External Systems
external: External Systems {
  NCEI
  NODD
  PACM
  website: Visualization Portal

  NCEI -> NODD: Publish archive to NODD

}

# - Ingest layer: authenticated upload endpoints and connector agents. CLI or Google Transport hard drives
# - Storage layer: object store with metadata catalog and lifecycle policies.
# - Processing layer: Manual cloud based workstaition (pam-ww) or batch scaling.
# - Visualization: Visualization for select products.  Possibly, building on the [SoundCOOP Visualization system](https://soundcoop.portal.axds.co)
# - Operations: monitoring, alerting, logs, backups, and cost management.
# - Export layer: dataset packaging and export workflows for downstream customers (e.g. NOAA/NCEI archive, PACM).

# Connections
operator -> obs: Collect raw observation
operator -> pamhub.ingest: Upload raw audio files and metadata
pamhub.ingest -> pamhub.storage: Write incoming data/metadata
pamhub.processing -> pamhub.storage: Read/write raw and processed data
analyst -> pamhub.processing: Manual processing, configure orchestration workflow
pamhub.export -> external

